= Alf.io CLI (prototype)

This is a starting for a cli to interact with Alf.io via cli.

IMPORTANT: This is a personal project not affiliated with https://alf.io/[Alf.io].
All rights for name belong to its respective owners.

== Usage

. Set `DB_URL` environment variable with full database connection url.
. Run command.

.example
 $ DB_URL="user:pass@postgresql://my-host:8888/my-db-name"

The command runs in endless loop, to stop it close the terminal or kill the process (^C).

The output displays the tickets grouped by category and status.
Status being:
* free: available to purchase
* acquired: purchase completed
* other statuses: purchase in process, cancelled or on error.

.output
----
CATEGORY            STATUS       COUNT/MAX
Blind                free         9/9
Blind + Workshops    free         12/12
Early                free         17/17
Early + Workshops    free         22/22
----

== Build

Projects is written in Rust[https://www.rust-lang.org/] and should compile in all major platforms with:

 $ cargo build --release

== Installation

Build and add file `alfio-cli` found in `target/release` to PATH.
